# Generated by Django 3.2.8 on 2021-11-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("responses", "0001_initial"),
        ("players", "0002_alter_player_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="responses",
            field=models.ManyToManyField(blank=True, to="responses.Response"),
        ),
    ]
