# Generated by Django 3.2.8 on 2021-11-17 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0003_alter_player_responses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="wallet",
        ),
    ]
