# Generated by Django 3.2.4 on 2021-07-09 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='wallet',
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_wallet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='from_wallet', to='currency.wallet'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_wallet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='to_wallet', to='currency.wallet'),
        ),
    ]
