# Generated by Django 3.2.4 on 2021-07-08 18:44

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='value',
        ),
        migrations.AddField(
            model_name='currency',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='transaction',
            name='state',
            field=django_fsm.FSMField(default='new', max_length=50),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('transactions', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currency.transaction')),
            ],
        ),
    ]
