# Generated by Django 3.2.6 on 2021-08-19 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('id_emojis', '0001_initial'),
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='emoji',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='currency', to='id_emojis.idemoji'),
        ),
    ]
