# Generated by Django 3.2.4 on 2021-07-27 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20210727_0235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='current_message',
            new_name='current_message_id',
        ),
    ]
