# Generated by Django 3.2.4 on 2021-07-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20210709_1248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankAccount',
        ),
    ]
