# Generated by Django 3.2.4 on 2021-07-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_transaction_emoji_lookup'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='emoji',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
