# Generated by Django 3.2.6 on 2021-08-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='emoji',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
