# Generated by Django 3.2.4 on 2021-07-28 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_auto_20210727_0331'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='emoji',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='team',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='currency.wallet'),
        ),
    ]
