# Generated by Django 3.2.4 on 2021-08-13 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discord_roles', '0001_initial'),
        ('team', '0002_auto_20210728_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='role',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discord_roles.role'),
        ),
    ]
