# Generated by Django 3.2.4 on 2021-08-13 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discord_guilds', '__first__'),
        ('team', '0003_team_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='guild',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discord_guilds.guild'),
        ),
    ]
