# Generated by Django 3.2.6 on 2021-08-19 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('id_emojis', '0001_initial'),
        ('team', '0003_alter_team_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='emoji',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='id_emojis.idemoji'),
        ),
    ]
