# Generated by Django 3.2.6 on 2021-08-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord_models", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="discord_id",
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
