# Generated by Django 3.2.6 on 2021-08-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord_models", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="name",
            field=models.CharField(default="", max_length=50, verbose_name="name"),
        ),
    ]
