# Generated by Django 3.2.6 on 2021-08-24 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord_models", "0002_role_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="guild",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="discord_models.guild",
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="guild",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="discord_models.guild",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="guild",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="discord_models.guild",
            ),
        ),
    ]
