# Generated by Django 3.2.6 on 2021-08-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord_models", "0002_alter_channel_discord_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="discord_id",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
