# Generated by Django 3.2.8 on 2021-11-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("MSG", "Message"),
                            ("CHT", "Change Team"),
                            ("CRO", "Create Role"),
                            ("CCA", "Create Category"),
                            ("CCH", "Create Team Channel"),
                            ("CCC", "Create Category Channel"),
                            ("CDR", "Create Dropdown"),
                            ("CBT", "Create Buttons"),
                            ("TSR", "Create Transaction"),
                            ("CMS", "Create Message"),
                            ("CTH", "Create Thread"),
                        ],
                        default="MSG",
                        max_length=3,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
            ],
        ),
    ]
