# Generated by Django 3.2.8 on 2021-11-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("MSG", "Message"),
                    ("CHT", "Change Team"),
                    ("CRO", "Create Role"),
                    ("CCA", "Create Category"),
                    ("CCH", "Create Team Channel"),
                    ("CVH", "Create Team Voice Channel"),
                    ("CCC", "Create Category Channel"),
                    ("CDR", "Create Dropdown"),
                    ("CBT", "Create Buttons"),
                    ("TSR", "Create Transaction"),
                    ("CMS", "Create Message"),
                    ("CTH", "Create Thread"),
                ],
                default="MSG",
                max_length=3,
            ),
        ),
    ]
