# Generated by Django 3.2.6 on 2021-08-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("MG", "Message"),
                    ("CT", "Change Team"),
                    ("RO", "Create Role"),
                    ("CA", "Create Category"),
                    ("CH", "Create Channel"),
                ],
                default="MG",
                max_length=2,
            ),
        ),
    ]
