# Generated by Django 3.2.6 on 2021-08-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_task_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("MG", "Message"),
                    ("CT", "Change Team"),
                    ("RO", "Create Role"),
                    ("CA", "Create Category"),
                    ("CH", "Create Channel"),
                    ("DR", "Create Dropdown"),
                ],
                default="MG",
                max_length=2,
            ),
        ),
    ]
