# Generated by Django 3.2.4 on 2021-08-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='player',
        ),
        migrations.AddField(
            model_name='task',
            name='payload',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('MG', 'Message'), ('CT', 'Change Team')], default='MG', max_length=2),
        ),
    ]
