# Generated by Django 3.2.6 on 2021-08-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('MG', 'Message'), ('CT', 'Change Team'), ('CRO', 'Create Role'), ('CCA', 'Create Category'), ('CCH', 'Create Channel'), ('CDR', 'Create Dropdown'), ('CTR', 'Create Transaction')], default='MG', max_length=3),
        ),
    ]
