# Generated by Django 3.2.4 on 2021-08-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20210812_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('MG', 'Message'), ('CT', 'Change Team'), ('AR', 'Add Role')], default='MG', max_length=2),
        ),
    ]
