# Generated by Django 3.2.8 on 2021-11-20 23:06

import django_fsm

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(default="")),
                (
                    "currency_type",
                    models.CharField(
                        choices=[
                            ("ADM", "Admin"),
                            ("COM", "Common"),
                            ("RAR", "Rare"),
                            ("LOG", "Logistics"),
                            ("HID", "Hidden"),
                            ("SPE", "Special"),
                        ],
                        default="HID",
                        max_length=3,
                    ),
                ),
                ("emoji", models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.TextField(default="")),
                ("cost", models.IntegerField(default=0)),
                ("embed_id", models.BigIntegerField(blank=True, null=True)),
                ("channel_id", models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("initiating_party_accepted", models.BooleanField(default=False)),
                ("receiving_party_accepted", models.BooleanField(default=False)),
                ("locked_in", models.BooleanField(default=False)),
                ("team_lookup", models.JSONField(blank=True, default=dict, null=True)),
                ("initiating_embed_id", models.BigIntegerField(null=True, unique=True)),
                ("receiving_embed_id", models.BigIntegerField(null=True, unique=True)),
                (
                    "state",
                    django_fsm.FSMField(default="initiating_party_view", max_length=50),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "modified_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("state", django_fsm.FSMField(default="new", max_length=50)),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="currencies.currency",
                    ),
                ),
                (
                    "from_wallet",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credits",
                        to="currencies.wallet",
                    ),
                ),
            ],
        ),
    ]
