# Generated by Django 3.2.6 on 2021-08-20 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        ("currencies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="initiating_party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="initiated_trades",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="receiving_party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receiving_trades",
                to="teams.team",
            ),
        ),
    ]
