# Generated by Django 3.2.8 on 2021-11-20 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        ("players", "0001_initial"),
        ("discord_models", "0001_initial"),
        ("currencies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="initiating_player",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transaction",
                to="players.player",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="to_wallet",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="debits",
                to="currencies.wallet",
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="discord_guild",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="discord_models.guild",
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="initiating_party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="initiated_trades",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="initiating_party_discord_trade_thread",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="initiating_discord_trade_thread",
                to="discord_models.channel",
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="receiving_party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receiving_trades",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="receiving_party_discord_trade_thread",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receiving_discord_trade_thread",
                to="discord_models.channel",
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="transactions",
            field=models.ManyToManyField(to="currencies.Transaction"),
        ),
        migrations.AddField(
            model_name="payment",
            name="transactions",
            field=models.ManyToManyField(to="currencies.Transaction"),
        ),
    ]
