# Generated by Django 3.2.8 on 2021-11-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="payment",
            name="completion_amount",
            field=models.IntegerField(default=0),
        ),
    ]
