# Generated by Django 3.2.6 on 2021-08-27 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="trade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="currencies.trade",
            ),
        ),
    ]
