# Generated by Django 3.2.6 on 2021-08-23 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="emoji_lookup",
        ),
        migrations.AddField(
            model_name="transaction",
            name="trade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="currencies.trade",
            ),
        ),
        migrations.AlterField(
            model_name="currency",
            name="emoji",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
