# Generated by Django 3.2.6 on 2021-08-28 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0003_alter_transaction_trade"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="initiating_party_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trade",
            name="receiving_party_accepted",
            field=models.BooleanField(default=False),
        ),
    ]
