# Generated by Django 3.2.6 on 2021-08-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0004_auto_20210827_2138"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trade",
            name="currency_lookup",
        ),
        migrations.AddField(
            model_name="trade",
            name="embed_id",
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
