# Generated by Django 3.2.8 on 2021-11-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0005_auto_20211123_0804"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="fundraising_amount",
            field=models.IntegerField(default=0),
        ),
    ]
