# Generated by Django 3.2.8 on 2021-11-03 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord_models", "0003_alter_channel_discord_id"),
        ("currencies", "0006_auto_20211021_1301"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trade",
            name="initiating_party_discord_thread",
        ),
        migrations.RemoveField(
            model_name="trade",
            name="receiving_party_discord_thread",
        ),
        migrations.AddField(
            model_name="trade",
            name="current_discord_trade_thread",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="current_discord_trade_thread",
                to="discord_models.channel",
            ),
        ),
    ]
