# Generated by Django 3.2.8 on 2021-11-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0008_auto_20211104_0808"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="trade",
        ),
        migrations.AddField(
            model_name="trade",
            name="transactions",
            field=models.ManyToManyField(to="currencies.Transaction"),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.TextField(default="")),
                ("price", models.IntegerField(default=0)),
                ("transactions", models.ManyToManyField(to="currencies.Transaction")),
            ],
        ),
    ]
