# Generated by Django 3.2.8 on 2021-11-04 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0009_auto_20211104_1046"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="price",
            new_name="cost",
        ),
    ]
