# Generated by Django 3.2.8 on 2021-11-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0010_rename_price_payment_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="locked_in",
            field=models.BooleanField(default=False),
        ),
    ]
