# Generated by Django 3.2.8 on 2021-11-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0011_trade_locked_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="embed_message",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
