# Generated by Django 3.2.8 on 2021-11-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0012_payment_embed_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="channel_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
