# Generated by Django 3.2.8 on 2021-11-17 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0013_payment_channel_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="embed_message",
            new_name="embed_id",
        ),
    ]
