# Generated by Django 3.2.8 on 2021-11-17 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0004_remove_player_wallet"),
        ("currencies", "0014_rename_embed_message_payment_embed_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="initiating_player",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transaction",
                to="players.player",
            ),
        ),
    ]
