# Generated by Django 3.2.4 on 2021-07-09 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stats', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedmessage',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages_authored', to='users.member'),
        ),
        migrations.AddField(
            model_name='loggedmessage',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='messages_mentioned_in', to='users.Member'),
        ),
    ]
