# Generated by Django 3.2.4 on 2021-07-28 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_member_player'),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedmessage',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_authored', to='users.member'),
        ),
    ]
