# Generated by Django 3.2.8 on 2021-11-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="abreviation",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
