# Generated by Django 3.2.6 on 2021-08-27 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord_models", "0001_initial"),
        ("teams", "0002_alter_team_general_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="menu_channel",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_menu_channel",
                to="discord_models.channel",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="general_channel",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_general_channel",
                to="discord_models.channel",
            ),
        ),
    ]
