# Generated by Django 3.2.8 on 2021-11-22 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord_models", "0001_initial"),
        ("teams", "0002_team_abreviation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="general_channel",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_general_channel",
                to="discord_models.channel",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="menu_channel",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_menu_channel",
                to="discord_models.channel",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="trade_channel",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_trade_channel",
                to="discord_models.channel",
            ),
        ),
    ]
