# Generated by Django 3.2.6 on 2021-08-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_auto_20210827_1135"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="bank_embed",
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
