# Generated by Django 3.2.6 on 2021-08-27 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0004_team_bank_embed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="bank_embed",
            new_name="bank_embed_id",
        ),
    ]
