# Generated by Django 3.2.8 on 2021-11-17 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0014_rename_embed_message_payment_embed_id"),
        ("teams", "0007_alter_team_wallet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="wallet",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team",
                to="currencies.wallet",
            ),
        ),
    ]
