# Generated by Django 3.2.4 on 2021-08-16 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("player", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discord_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("is_bot", models.BooleanField(default=False)),
                ("can_admin_bot", models.BooleanField(default=False)),
                (
                    "player",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discord_member",
                        to="player.player",
                    ),
                ),
            ],
        ),
    ]
