# Generated by Django 3.2.4 on 2021-06-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('is_bot', models.BooleanField(default=False)),
                ('can_admin_bot', models.BooleanField(default=False)),
            ],
        ),
    ]
